### ISSUE TITLE
Use options for consumable names

### ISSUE THREAD

**Issue by humburg** [Malekal4699/LightsHUD#1]
@Malekal4699 Thanks for bringing this back to life for v0.9. If you are willing to fix some of the existing issues, here is one that should be easy to address. The module currently has options to provide the names of consumables for the torch and lantern. But they aren't actually used as the names are hard-coded here:
https://github.com/Malekal4699/TorchLight/blob/681812b9b814654666760d79f36757ae236804ae/scripts/torchlight.js#L72
and here:
https://github.com/Malekal4699/TorchLight/blob/681812b9b814654666760d79f36757ae236804ae/scripts/torchlight.js#L79
Replacing those strings with the value of the respective input field would hook everything up properly, I think.

**Comment by gioppoluca** [comment]
Also "Lantern, hooded" and "Lantern, Bulleyes" is hardcoded and it could not work if you have changed the item (BTW in SRD items now these are "Hooded Lantern" and "Bullseye Lantern" so also these 2 or preferably an array should be configurable

**Comment by Malekal4699** [comment]
Going to move this one from bug to enhancement.
I plan on changing the setup a bit to allow custom names for light sources as well as consumables.

**Comment by Malekal4699** [comment]
Done! You can now edit the name to look for in the settings.
