### ISSUE TITLE
LightsHUD - Bug - 

### ISSUE THREAD

**Issue by Vazzimolo** [Malekal4699/LightsHUD#12]
Une erreur d'affichage sur la feuille de personnage de PF2 lorsque Minimal UI est actif avec LightsHUD.
https://media.discordapp.net/attachments/715986155975344211/933434872649875456/unknown.png

Cdt.

**Comment by Malekal4699** [comment]
Bonjour! On s'attend à voir quoi? Je n'ai jamais utiliser l'autre module.

**Comment by Sasmira** [comment]
> Bonjour! On s'attend à voir quoi? Je n'ai jamais utiliser l'autre module.

alors d'apres ce qu'il a mis sur le discord on doit voir un truc comme ca 
<img src="https://cdn.discordapp.com/attachments/715986155975344211/933434872649875456/unknown.png">

**Comment by Vazzimolo** [comment]
Bonjour,

On doit avoir cet affichage :
***@***.***

C’est quand même plus mieux.

Cdt.

De : ***@***.***>
Envoyé le :mercredi 19 janvier 2022 20:24
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Malekal4699/LightsHUD] LightsHUD - Bug - (Issue #12)


Bonjour! On s'attend à voir quoi? Je n'ai jamais utiliser l'autre module.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMalekal4699%2FLightsHUD%2Fissues%2F12%23issuecomment-1016793854&data=04%7C01%7C%7Ca68ac6524f4f492f441d08d9db815583%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782170796881199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kOG47CkfYZq8fW%2FIKTW9LbqJ4QmZJeW7zDB763KdXog%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXMCZNMTOKC6YHXLALC5VJTUW4FXLANCNFSM5MKZKRGA&data=04%7C01%7C%7Ca68ac6524f4f492f441d08d9db815583%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782170796881199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=s2LMS0F1lNpmHQkaFzewRdTIM%2BvzdshKuXeILcWYSV4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca68ac6524f4f492f441d08d9db815583%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782170796881199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4L6ANK157Xo5bDa6kZordO2JhZyxhxVWa2mEDhXjOHg%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca68ac6524f4f492f441d08d9db815583%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782170796881199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=O2RD%2FwdSGBCEt6hLj121LWlmXWTm2limcvXGbvenj%2Fo%3D&reserved=0>.

**Comment by Malekal4699** [comment]
Salut, l'image n'affiche pas. serait mieux de la copier direct sur le site que par un reply au courriel. ;) Merci!

**Comment by Sasmira** [comment]
> Salut, l'image n'affiche pas. serait mieux de la copier direct sur le site que par un reply au courriel. ;) Merci!

Désolé mais je crois que tu gagneras du temps en lui parlant directement sur le discord :D

**Comment by Malekal4699** [comment]
> > Salut, l'image n'affiche pas. serait mieux de la copier direct sur le site que par un reply au courriel. ;) Merci!
> 
> Désolé mais je crois que tu gagneras du temps en lui parlant directement sur le discord :D

haha possible.

**Comment by Malekal4699** [comment]
Tout semble bien fonctionner. J'ignore quel est l'ecran que tu affiche en erreur. 

![image](https://user-images.githubusercontent.com/78604153/150207889-2c163275-482f-4b41-b930-9ddf8aa84757.png)

**Comment by Malekal4699** [comment]
Ok je viens de trouver. Le bug est avec minimalUI ET LightsHUD, lorsque la localisation est en francais.

**Comment by Vazzimolo** [comment]
Bravo et merci.
