### ISSUE TITLE
LightsHUD - Bug - not compatible with v9?

### ISSUE THREAD

**Issue by playest** [Malekal4699/LightsHUD#16]
**Describe the bug**
Is this module supposed to be compatible with v9? I have build 238.

I tried to use the torch button but it doesn't work. (Note that the light spell is working)

I have identifier multiples problems:
- The scripts doesn't detect correctly if a torch is in the inventory, in `hasItemInInventory` the `if (item.data.quantity > 0) hasItem = true;` should be `if (item.data.data.quantity > 0) hasItem = true;`, now the torch button is enabled correctly
- When I click on it I get
```
TypeError: Cannot set property token of #<Actor> which has only a getter
    at ChatSpeakerData._initializeSource (data.mjs:134)
    at new DocumentData (data.mjs:45)
    at new ChatSpeakerData (data.mjs:587)
    at ChatMessageData._initializeType (data.mjs:232)
    at ChatMessageData._initialize (data.mjs:201)
    at new DocumentData (data.mjs:51)
    at new ChatMessageData (data.mjs:629)
    at new Document (document.mjs:47)
    at new BaseChatMessage (documents.mjs:392)
    at new <anonymous> (foundry.js:10442)
onError @ foundry.js:316
_preCreateDocumentArray @ foundry.js:9899
_createDocuments @ foundry.js:9837
create @ backend.mjs:96
async function (async)
create @ backend.mjs:93
createDocuments @ document.mjs:338
create @ document.mjs:439
onButtonClick @ LightsHUD.js:687
(anonymous) @ LightsHUD.js:47
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

- There is also an offset variable which is used in a forEach, apparently this variable is not defined for Map (`actor.data.items` is a Map), I fixed it (I think?) like this (see comments)
```js
actor.data.items.forEach((item, offset) => {
    if(item.name.toLowerCase() === itemToCheck.toLowerCase()) {
        if(item.data.quantity > 0) {
            hasItem = true;
            actor.updateOwnedItem({
                _id: actor.data.items[offset]._id,
                "data.quantity": actor.data.items[offset].data.quantity - 1, // replace `actor.data.items[offset]` with `item`
            });
        }
    }
});
```

- After doing that the module was still not working so I kind of gave up, maybe you could give me some pointer?

**To Reproduce**
1. Run v9
2. Try to use the torch button

**Comment by Malekal4699** [comment]
Hi, yes, I'm working on resolving these. At the moment, only works if no checks and consumes are being made.

**Comment by Malekal4699** [comment]
https://github.com/Malekal4699/LightsHUD/tree/Hardcoded-Settings 

is the work in progress branch for these issues. In the latest commit, check availability works without consuming. Ironing out the kinks of the consume option.

**Comment by Malekal4699** [comment]
I believe this is now fixed, rest is in progress.
