### ISSUE TITLE
LightsHUD - Bug - Torch/light spells don't turn off

### ISSUE THREAD

**Issue by tehguitarist** [Malekal4699/LightsHUD#18]
Hey, you're probably aware as you work through, just played a session with the new update (of both foundry and the module) and clicking the torch icon wasn't turning it off, though turned on and looked great! Had to manually remove the light from the token.

The torch and light tokens also seemed to stay orange highlighted whether they were on or not. 

Like I said, you're probably aware, but I'm also happy to get more details if needed!

**Comment by Malekal4699** [comment]
Hi, I guess it's safe to assume that those are Actor linked tokens. Working on it.

**Comment by doomspectre** [comment]
I had the same issue after **updating** my world, mod, and system (5e).
On a hunch, I created a new world and enabled the mod and the lights toggle on and off without issue.
Went back to my first world, where I was  having the persistent torch issue, and disabled/re-enabled mod. Still had the issue, but I noticed the token in question was having it's light radius set.
![image](https://user-images.githubusercontent.com/32599079/151592986-23df5a24-c28d-4c3a-873f-cd541e2e9fc1.png)
After toggling torch button, then removing the values from token light settings, then re-activating torch button on, the torches toggle on and off as expected.

So it seems like something, possibly updating but not for certain, is causing torch to affect token light, but removing token light and disabling/re-enabling mod fixed the issue.

**Comment by Malekal4699** [comment]
Hi I'm working on that part. This is due to token being linked to an actor. There's a mix up in which document gets the flag.

Should have no problem with unlinked tokens.

**Comment by TenguGrib** [comment]
Also having the same issue, came to report it but I see you're already on it. Keep up the good work, the module is awesome and I'm really glad that it's back and functioning again.

**Comment by Malekal4699** [comment]
deleting the token also works, from my tests and troubleshootings

**Comment by Malekal4699** [comment]
Tested on latest version. Appear to be fixed.
Closing.
