### ISSUE TITLE
LightsHUD - Bug - Incorrect light option + desynchronized intensity settings

### ISSUE THREAD

**Issue by Vesselchuck** [Malekal4699/LightsHUD#22]
**Describe the bug**
When any of the three light options is switched on, it is always the Light cantrip that is switched on. It does not matter whether the Lantern or Torch is switched on, it is always the Light cantrip that is switched on. The settings are set to custom, before the last module update everything was working fine.
There is also another bug, it is about colour intensity not being synchronized with intensity in settings.

**To Reproduce**
1. Go to Token HUD by clicking RMB on any given token
2. Click on any of LightsHUD light options
3. See the error

**Expected behavior**
When one of the three light options is switched on, it is the selected light that must be switched on, not the Light cantrip.

**Screenshots**
![Screenshot_13](https://user-images.githubusercontent.com/70449411/152988206-bb71e72c-0b23-48a4-87b0-db201fdd3941.png)
My LightsHUD settings:
![Screenshot_11](https://user-images.githubusercontent.com/70449411/152986332-5b4b4249-1815-43a9-a371-2cdb82e64417.png)
![Screenshot_12](https://user-images.githubusercontent.com/70449411/152986337-cdc55222-64d8-441e-91aa-1ea7887e68e6.png)
![Screenshot_8](https://user-images.githubusercontent.com/70449411/152986340-a1cacf24-53bd-46bd-9a64-8d2126bdc1be.png)
![Screenshot_9](https://user-images.githubusercontent.com/70449411/152986346-768c10bf-a7be-4a83-954f-fd352789af29.png)
![Screenshot_10](https://user-images.githubusercontent.com/70449411/152986358-a0e72e8d-0256-47d0-a37c-110c8e340639.png)

**Comment by Malekal4699** [comment]
Hi, already working on this with issue #18, it's taking a little while due to the overhaul in the background.

**Comment by Vesselchuck** [comment]
> 

That's great, I can''t wait to get it fixed, as at the moment I'm having to write every value manually.

**Comment by Malekal4699** [comment]
First part appear to be fixed in the latest version.
I will add the missing sliders.

**Comment by Malekal4699** [comment]
Nevermind, already corrected.
