### ISSUE TITLE
LightsHUD - Bug - Player's can't use module

### ISSUE THREAD

**Issue by ctbritt** [Malekal4699/LightsHUD#23]
**Describe the bug**
the icons are grayed out on the players side.

**Expected behavior**
Players can use the icons to turn on and off lights

**Screenshots**
<img width="116" alt="Screen Shot 2022-02-08 at 2 53 00 PM" src="https://user-images.githubusercontent.com/4516034/153064960-e428ef40-d29e-4643-b7b6-0d5b1865c77d.png">

**Additional context**

**Comment by ctbritt** [comment]
Yes, it is checked.

**Comment by Malekal4699** [comment]
Appears to be working with latest. 
Closing.
