### ISSUE TITLE
LightsHUD - Bug - Player can't turn off torch / oil lamp if he used his last one

### ISSUE THREAD

**Issue by remiverdel** [Malekal4699/LightsHUD#24]
**Describe the bug**
When a player uses Torches or Oil Lamp, it works fine except when he runs out of it. The button to turn on/off becomes greyed out and he can't turn his light off.

**Comment by Malekal4699** [comment]
Works for unlinked token. Issue with linked token.

**Comment by Malekal4699** [comment]
Hi, I made a quick fix, and it seem to work.
can you install https://github.com/Malekal4699/LightsHUD/archive/refs/heads/24-lightshud---bug---player-cant-turn-of.zip
And check if you can reproduce?
Thanks

**Comment by Malekal4699** [comment]
Nvm, forgot it was player side.
