### ISSUE TITLE
LightsHUD - Bug - No Setting for custom "Light spell" name

### ISSUE THREAD

**Issue by remiverdel** [Malekal4699/LightsHUD#25]
**Describe the bug**
I'm a French player and it seems now Torch and Oil Lamp have a custom name in the settings but I can't find a custom name to input the French translation of the Light Cantrip so it doesn't seem to work.

**Comment by Malekal4699** [comment]
Hi, I can see how that's an issue...
Salut, je vois comment ceci peut etre un probleme...

Je vais ajouter le setting.

**Comment by Malekal4699** [comment]
Setting ajouté. Sera dispo dans le prochain release.
