### ISSUE TITLE
LightsHUD - Bug - Light doesn't turn off on first click, only on second but uses 2 charges

### ISSUE THREAD

**Issue by remiverdel** [Malekal4699/LightsHUD#26]
**Describe the bug**
Lights seems to only turn off on the second clicked when turned on for the first time. But when I click to turn it off and it doesn't work the first time, it still depletes my ressources. It seems it may be getting out of sync and remove a charge on turn on instead of on turn off maybe that's why I usually can't turn off my last remaining torch because it depleted the last one as I turned it on? (ref to my other Bug report)

**Comment by Malekal4699** [comment]
Linked token?

**Comment by Malekal4699** [comment]
A token is either linked or not to the actor it represent. Usually players. It's working fine for unlinked tokens, I'm working on fixing the hud when the token is linked

**Comment by Malekal4699** [comment]
Tests on current version seem to have this issue now working.
Closing.
