### ISSUE TITLE
LightsHUD - Bug - when updating torch settings, Torch animation type breaks

### ISSUE THREAD

**Issue by allanmohr** [Malekal4699/LightsHUD#28]
**Describe the bug**
When changing the default bright/dim radius of the Torch and custom hex color, the animation type of Torch is broken.  The torch light is emitted, but there is no torch animation - just the illuminated circle.  I've uninstalled the mod and reinstalled but the settings file must be persistent somewhere that I cannot find.  I wish there was a reset button for this mod to reset all features back.

**To Reproduce**
1. Go to into settings
2. Choose custom configuration for torch
3. Change dim/bright/custom color options

**Expected behavior**
The torch should appear animated and flickering when activated

**Screenshots**
Screenshot attached

**Additional context**
![Screen Shot 2022-03-16 at 8 24 01 AM](https://user-images.githubusercontent.com/6403920/158590469-2b0cf67c-fcda-4929-8922-b597981dc0b9.png)

**Comment by TheTeal** [comment]
This issue effectively makes this mod completely unusable unless you install it and then don't touch any settings at all - is there any timeline on a fix? Thanks.

**Comment by Malekal4699** [comment]
Fixed. Pushing a new release.
