### ISSUE TITLE
Debug mode still enabled

### ISSUE THREAD

**Issue by tagnullde** [Malekal4699/LightsHUD#3]
Happy new year,

Just wanna let you know that you left the debug mode enabled.
![image](https://user-images.githubusercontent.com/44159008/147976190-c9907e11-af48-490f-baab-f51e261a8eac.png)

Regards
x41

**Comment by Malekal4699** [comment]
Hi,

There's a setting for debug? Make sure it is off.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/78604153/147978610-a772b9d6-56f1-4313-862f-1ceb7e4e86c2.png">

**Comment by tagnullde** [comment]
That option wasn't present before. From the Changelog I suspect you just added it. 

Thank you for the option and quick response.
