### ISSUE TITLE
LightsHUD - Bug - Preset light options are not configured as expected.

### ISSUE THREAD

**Issue by Grizwold53** [Malekal4699/LightsHUD#34]
**Describe the bug**
When selecting one of the "preset" light types, the displayed light is different from what's configured

**To Reproduce**
1. Go into settings
2. Choose a "type of light" (example below, Lantern: 9 - Bullseye, Dim
3. Press lantern button on token

**Expected behavior**
A bullseye lantern emits from selected token, with default light color and a limited emission angle (60ft cone).

**Actual behavior**
Token light color is set to red (#ff0000), token animation is "ghostly light", light emission angle is 360 degrees.

**Screenshots**
Attached

**Additional context**
Testing done on Foundry v9 build 255, with Starfinder system v0.18.2. No other modules were enabled. 

![light](https://user-images.githubusercontent.com/88157602/160166947-783ced31-c5f1-4e56-863b-0e869eb02bdb.JPG)

**Comment by Malekal4699** [comment]
Corrected and released.
