### ISSUE TITLE
Can't use lantern or torch on character that has both

### ISSUE THREAD

**Issue by ctbritt** [Malekal4699/LightsHUD#4]
Have lanterns, torches and flasks of oil equipped. Only the light cantrip button works. No errors in the console.

**Comment by Malekal4699** [comment]
Hi, while I check and sort this out, you can check the settings and remove the check on these.

![image](https://user-images.githubusercontent.com/78604153/147983090-4e24ea14-f1b4-4d9d-bb55-dd6d0db146d4.png)

**Comment by gioppoluca** [comment]
Same here but I'm checking as a GM and if I activate as GM it does not allow to activate torch or lantern.
Light cantrip works

**Comment by gioppoluca** [comment]
unckeched as GM allows to activate anything

**Comment by Malekal4699** [comment]
Hi, please download latest update and recheck.

**Comment by Malekal4699** [comment]
Fixed with latest release. Please read notes.
