### ISSUE TITLE
[Bug] Lantern animation

### ISSUE THREAD

**Issue by lucaspicerni** [Malekal4699/LightsHUD#40]
Toggle the lantern on when using custom configurations always use the "pulse" animations instead of the chosen one.

**Comment by Th3Rom3** [comment]
I can confirm this bug. In fact it seems to apply the values entered for the light spell option.

**Comment by Malekal4699** [comment]
Damn I had an issue with the commits and branches prior to latest release. That's what you get when you cut and paste stuff...
I'll fix that.

**Comment by lucaspicerni** [comment]
Thank you for the hard work!

**Comment by Malekal4699** [comment]
Yup... damn cut and paste.
![image](https://user-images.githubusercontent.com/78604153/162093519-daf86757-9d3c-4623-b2a1-15877b1f37da.png)

**Comment by Malekal4699** [comment]
0.10.8g is out.
