### ISSUE TITLE
LightsHUD - Bug - 

### ISSUE THREAD

**Issue by seanwilliams1964** [Malekal4699/LightsHUD#41]
**Describe the bug**
When the context menu for torch is selected for a token, the configuration values for Light Spell are applied.

**To Reproduce**
1. Go to Configure Settings for LightsHUD and set custom settings for torch and Light Spell (make them noticeably different)
2. Right-Click any token to open the context menu
3. Select the torch icon
4. See that the settings for the Light Spell are applied.

**Expected behavior**
The settings for torch should be displayed.

**Screenshots**

**Additional context**
![Light](https://user-images.githubusercontent.com/1427618/163511334-491005c8-c3bc-43f6-bdd4-3940e56d17e7.png)
![Torch](https://user-images.githubusercontent.com/1427618/163511341-2a316580-ac7a-45b1-a4d0-12cb7835b520.png)
![Context](https://user-images.githubusercontent.com/1427618/163511346-ac01821a-51cc-42fe-b9dc-49cc6e042849.png)
![Applied](https://user-images.githubusercontent.com/1427618/163511351-76889227-d785-4b1e-bb0f-b8eb5d71a807.png)

**Comment by Malekal4699** [comment]
Hi, following a concussion this spring, I find myself having to shy await from screens as much as possible for a while. Good news is, user p4535992 has forked LightsHUD, adding many things I wanted to do, doing it better. Please have a look here: https://github.com/p4535992/foundryvtt-lights-hud-ate

dev is halted for the moment on this module.
