### ISSUE TITLE
LightsHUD - Bug - Can't toggle light on specific token

### ISSUE THREAD

**Issue by Orionox** [Malekal4699/LightsHUD#43]
**Describe the bug**
I have a token with torches and the torch appears to be toggled ON, but no light is being emitted from the token and I cannot toggle the torch off. 
Edit: while trying to reproduce the effect, I have discovered another issue. When toggling the light on and off three times, the light gets stuck on even if the button changes. Sort of the opposite issue of the first one I found. This one can be fixed with a restart though. This secondary bug appears to be related to the "consume item" setting. 

**To Reproduce**
I was able to reproduce it. If I have a torch-lit, then apply an active effect that gives darkvision then the button breaks and will no longer toggle on and off, defaulting to off, and the only way to fix it is to delete the token and replace it on the scene. Additionally, if you toggle a light on, then refresh the scene the button will break and default to off, and the only way to fix it is to delete the token and replace it on the scene. 

**Expected behavior**
When I click the torch button it should toggle the torch lighting, but the button is staying toggled ON without emitting any light. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/20059838/165758739-be5c968f-804a-4749-855b-56640f0f4374.PNG)

edit: I believe its related, but the token in question also cannot hold a lighting settings through a refresh/restart

**Comment by Orionox** [comment]
![Capture](https://user-images.githubusercontent.com/20059838/165814083-3bd0520a-b315-477d-af7a-7cc4cf22a8b7.PNG)

**Comment by Orionox** [comment]
I was able to reproduce it. If I have a torch-lit, then apply an active effect that gives darkvision then the button breaks and will no longer toggle on and off.

**Comment by Malekal4699** [comment]
Hi, following a concussion this spring, I find myself having to shy await from screens as much as possible for a while. Good news is, user p4535992 has forked LightsHUD, adding many things I wanted to do, doing it better. Please have a look here: https://github.com/p4535992/foundryvtt-lights-hud-ate

dev is halted for the moment on this module.
