### ISSUE TITLE
LightsHUD - Bug - Lights are super brigght

### ISSUE THREAD

**Issue by JustinCamden** [Malekal4699/LightsHUD#44]
**Describe the bug**
All the lights are super bright and seem to wash out the colors now.

**To Reproduce**
1. Enable the Torch light on any token.
2. Observe that the light is very bright and washes out the other colors in the scene.

**Expected behavior**
The light should be less instance.

**Screenshots**
![image](https://user-images.githubusercontent.com/14845045/166185728-902c94c4-c329-41d2-8931-38a804827f06.png)

**Additional context**

**Comment by Malekal4699** [comment]
Hi, following a concussion this spring, I find myself having to shy await from screens as much as possible for a while. Good news is, user p4535992 has forked LightsHUD, adding many things I wanted to do, doing it better. Please have a look here: https://github.com/p4535992/foundryvtt-lights-hud-ate

dev is halted for the moment on this module.
