### ISSUE TITLE
LightsHUD - Bug -  Custom names for torches or light etc doesn't work

### ISSUE THREAD

**Issue by remiverdel** [Malekal4699/LightsHUD#8]
**Describe the bug**

**To Reproduce**
0. Check player has right to use the LightHUD module option.
1. Rename torch in the settings in "Torche" (French localization)
2. Put a "Torche" inside the player inventory
3. Connect as the player (not the GM)
4. Try to click on the torch icon
5. Torch icon is greyed out, player can't light up his own torch
6. "Torche" item doesn't deplete.

**Expected behavior**
The player should be able to light up his own torch and it should deplete the number he has.

**Additional context**
I'm using French DND so I need to put the French name of items inside the Module Settings but it doesn't seem to work.

**Comment by Malekal4699** [comment]
Hi, 
That's because the values are hardcoded rather than using the fields. I need to look at this.
Thanks for bringing it up..

**Comment by Malekal4699** [comment]
not sure if the regression broke this again.

**Comment by Malekal4699** [comment]
verified. fixed.
